### ISSUE TITLE
Table of contents should have no vertical padding

### ISSUE THREAD

**Issue by AlexDaniel** [thi-ng/org-theme#10]
Actually, I am not sure about this one.

But try this:
- Create a document with many headings
- Change height of your window slightly, so that some part of the ToC is cut off (does not fit into the window vertically)
- Scrollbar should appear
- If you scroll down, can you see the last ToC item?

I can't, but I already have a lot of modifications to the style, so perhaps my bug report is not valid. Try it yourself.

I did this to fix it:

``` css
@media screen {
    #table-of-contents {
        padding: 0 0 0 2em; /* was 2em 0 2em 2em */
    }
    #table-of-contents h2 {
        margin-top: 1.5em; /* was 0 */
    }
}
```

**Comment by postspectacular** [comment]
Hi @AlexDaniel - firstly thanks for all these submissions and MASSIVE apologies for only noticing them now (due to another new issue from today)... I haven't really used this project in a while, but adding a scrollbar for the TOC should just be this:

```css
#table-of-contents {
    ...
    overflow-y: auto;
}
```

Will try to push an update ASAP
