### ISSUE TITLE
No fallback font in pre elements

### ISSUE THREAD

**Issue by AlexDaniel** [thi-ng/org-theme#13]
It is:

``` css
pre {
    font-family: Inconsolata;
    …
}
```

It should be:

``` css
pre {
    font-family: Inconsolata, monospace;
    …
}
```
