### ISSUE TITLE
pre background is laggy

### ISSUE THREAD

**Issue by AlexDaniel** [thi-ng/org-theme#9]
`pre` elements are styled like this:

``` css
pre {
    background-color: #f8f8f8;
    background-size: 8px 8px;
    background-image: linear-gradient(135deg, transparent 25%, rgba(0, 0, 0, 0.02) 25%, rgba(0, 0, 0, 0.02) 50%, transparent 50%, transparent 75%, rgba(0, 0, 0, 0.02) 75%, rgba(0, 0, 0, 0.02));
}
```

This may not be noticeable on faster machines, but this kind of background lags way too much on some computers. Perhaps it also depends on the browser (I am using firefox), but I recommend to just throw it away.

This zebra-like background makes code hard to read anyway, plain gray background is probably better.
